services:
  - type: web
    name: my-flask-app
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "python app.py"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: 3306
      FLASK_ENV: ${FLASK_ENV}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    instanceType: "small"  # Adjust based on your app's needs
    regions:
      - oregon

  - type: database
    name: mysql-database
    engine: mysql
    version: 5.7
    plan: free  # Choose the plan that fits your needs
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthCheck:
      path: "/"
      intervalSeconds: 60
      timeoutSeconds: 10
      maxAttempts: 3

  - type: network
    name: cooking_compass_net
    subnets:
      - cidr: 10.0.0.0/16

# Optional: For MySQL persistent data
volumes:
  - name: mysql-data
    driver: local
